SET SERVEROUTPUT ON

CREATE OR REPLACE procedure largeurTables() 
return number
is
tailleDest number;
c1,c2,c3,c4,c5,c6,c7,c8,c9,c10 number;
begin
 
	SELECT DATA_LENGTH into c1 FROM ALL_TAB_COLUMNS WHERE TABLE_NAME='DESTINATION' AND COLUMN_NAME='ID_DEST'; 
	SELECT DATA_LENGTH into c2 FROM ALL_TAB_COLUMNS WHERE TABLE_NAME='DESTINATION' AND COLUMN_NAME='Nom_Destination'; 
	SELECT DATA_LENGTH into c3 FROM ALL_TAB_COLUMNS WHERE TABLE_NAME='DESTINATION' AND COLUMN_NAME='Pays'; 
	dbms_output.put_line('taille table destination = :' || TO_CHAR(c1+c2+c3) );

	SELECT DATA_LENGTH into c1 FROM ALL_TAB_COLUMNS WHERE TABLE_NAME='Circuit' AND COLUMN_NAME='ID_Circuit'; 
	SELECT DATA_LENGTH into c2 FROM ALL_TAB_COLUMNS WHERE TABLE_NAME='Circuit' AND COLUMN_NAME='Nom_Circuit'; 
	dbms_output.put_line('taille table circuit = :' || TO_CHAR(c1+c2) );

	SELECT DATA_LENGTH into c1 FROM ALL_TAB_COLUMNS WHERE TABLE_NAME='Assoc_Dest_Circuit' AND COLUMN_NAME='ID_Dest'; 
	SELECT DATA_LENGTH into c2 FROM ALL_TAB_COLUMNS WHERE TABLE_NAME='Assoc_Dest_Circuit' AND COLUMN_NAME='ID_Circuit'; 
	dbms_output.put_line('taille table assoc_desc_circuit = :' || TO_CHAR(c1+c2) );

	SELECT DATA_LENGTH into c1 FROM ALL_TAB_COLUMNS WHERE TABLE_NAME='HOTEL' AND COLUMN_NAME='ID_Hotel'; 
	SELECT DATA_LENGTH into c2 FROM ALL_TAB_COLUMNS WHERE TABLE_NAME='HOTEL' AND COLUMN_NAME='ID_Dest'; 
	SELECT DATA_LENGTH into c3 FROM ALL_TAB_COLUMNS WHERE TABLE_NAME='HOTEL' AND COLUMN_NAME='Nom_Hotel'; 
	SELECT DATA_LENGTH into c4 FROM ALL_TAB_COLUMNS WHERE TABLE_NAME='HOTEL' AND COLUMN_NAME='Addresse'; 
	SELECT DATA_LENGTH into c5 FROM ALL_TAB_COLUMNS WHERE TABLE_NAME='HOTEL' AND COLUMN_NAME='ID_Classe'; 
	SELECT DATA_LENGTH into c6 FROM ALL_TAB_COLUMNS WHERE TABLE_NAME='HOTEL' AND COLUMN_NAME='capac_S'; 
	SELECT DATA_LENGTH into c7 FROM ALL_TAB_COLUMNS WHERE TABLE_NAME='HOTEL' AND COLUMN_NAME='capac_D'; 
	dbms_output.put_line('taille table Hotel = :' || TO_CHAR(c1+c2+c3+c4+c5+c6+c7) );

	SELECT DATA_LENGTH into c1 FROM ALL_TAB_COLUMNS WHERE TABLE_NAME='Classe_Hotel' AND COLUMN_NAME='ID_Classe'; 
	SELECT DATA_LENGTH into c2 FROM ALL_TAB_COLUMNS WHERE TABLE_NAME='Classe_Hotel' AND COLUMN_NAME='Prix_S'; 
	SELECT DATA_LENGTH into c3 FROM ALL_TAB_COLUMNS WHERE TABLE_NAME='Classe_Hotel' AND COLUMN_NAME='Prix_D'; 
	dbms_output.put_line('taille table Classe_Hotel = :' || TO_CHAR(c1+c2+c3) );

	SELECT DATA_LENGTH into c1 FROM ALL_TAB_COLUMNS WHERE TABLE_NAME='Sejour' AND COLUMN_NAME='ID_Sejour'; 
	SELECT DATA_LENGTH into c2 FROM ALL_TAB_COLUMNS WHERE TABLE_NAME='Sejour' AND COLUMN_NAME='Duree'; 
	SELECT DATA_LENGTH into c3 FROM ALL_TAB_COLUMNS WHERE TABLE_NAME='Sejour' AND COLUMN_NAME='Description'; 
	SELECT DATA_LENGTH into c4 FROM ALL_TAB_COLUMNS WHERE TABLE_NAME='Sejour' AND COLUMN_NAME='Coeff'; 
	dbms_output.put_line('taille table destination = :' || TO_CHAR(c1+c2+c3+c4) );

	SELECT DATA_LENGTH into c1 FROM ALL_TAB_COLUMNS WHERE TABLE_NAME='Assoc_Prix_Sejour_Circuit' AND COLUMN_NAME='ID_Circuit'; 
	SELECT DATA_LENGTH into c2 FROM ALL_TAB_COLUMNS WHERE TABLE_NAME='Assoc_Prix_Sejour_Circuit' AND COLUMN_NAME='ID_Sejour'; 
	SELECT DATA_LENGTH into c3 FROM ALL_TAB_COLUMNS WHERE TABLE_NAME='Assoc_Prix_Sejour_Circuit' AND COLUMN_NAME='Prix'; 
	dbms_output.put_line('taille table Assoc_Prix_Sejour_Circuit = :' || TO_CHAR(c1+c2+c3) );

	SELECT DATA_LENGTH into c1 FROM ALL_TAB_COLUMNS WHERE TABLE_NAME='Vol' AND COLUMN_NAME='ID_Vol'; 
	SELECT DATA_LENGTH into c2 FROM ALL_TAB_COLUMNS WHERE TABLE_NAME='Vol' AND COLUMN_NAME='ID_Dest'; 
	SELECT DATA_LENGTH into c3 FROM ALL_TAB_COLUMNS WHERE TABLE_NAME='Vol' AND COLUMN_NAME='Prix_Enfant'; 
	SELECT DATA_LENGTH into c4 FROM ALL_TAB_COLUMNS WHERE TABLE_NAME='Vol' AND COLUMN_NAME='Prix_Adulte'; 
	dbms_output.put_line('taille table Vol = :' || TO_CHAR(c1+c2+c3+c4) );

	SELECT DATA_LENGTH into c1 FROM ALL_TAB_COLUMNS WHERE TABLE_NAME='Client' AND COLUMN_NAME='ID_Client'; 
	SELECT DATA_LENGTH into c2 FROM ALL_TAB_COLUMNS WHERE TABLE_NAME='Client' AND COLUMN_NAME='Addresse'; 
	SELECT DATA_LENGTH into c3 FROM ALL_TAB_COLUMNS WHERE TABLE_NAME='Client' AND COLUMN_NAME='Tel'; 
	SELECT DATA_LENGTH into c4 FROM ALL_TAB_COLUMNS WHERE TABLE_NAME='Client' AND COLUMN_NAME='Nom'; 
	SELECT DATA_LENGTH into c5 FROM ALL_TAB_COLUMNS WHERE TABLE_NAME='Client' AND COLUMN_NAME='Prenom'; 
	SELECT DATA_LENGTH into c6 FROM ALL_TAB_COLUMNS WHERE TABLE_NAME='Client' AND COLUMN_NAME='Age'; 
	SELECT DATA_LENGTH into c7 FROM ALL_TAB_COLUMNS WHERE TABLE_NAME='Client' AND COLUMN_NAME='Email'; 
	SELECT DATA_LENGTH into c8 FROM ALL_TAB_COLUMNS WHERE TABLE_NAME='Client' AND COLUMN_NAME='Classe_sociale'; 
	SELECT DATA_LENGTH into c9 FROM ALL_TAB_COLUMNS WHERE TABLE_NAME='Client' AND COLUMN_NAME='ID_Dest_Preferee'; 
	SELECT DATA_LENGTH into c10 FROM ALL_TAB_COLUMNS WHERE TABLE_NAME='Client' AND COLUMN_NAME='Investissement_Moyen'; 
	dbms_output.put_line('taille table Client = :' || TO_CHAR(c1+c2+c3+c4+c5+c6+c7+c8+c9+c10) );
		 
		 --manque le facturation mais pouet

end;
/

show errors;

